# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cheta.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StartBut = QtWidgets.QPushButton(self.centralwidget)
        self.StartBut.setGeometry(QtCore.QRect(500, 240, 81, 31))
        self.StartBut.setObjectName("StartBut")
        self.StopBut = QtWidgets.QPushButton(self.centralwidget)
        self.StopBut.setGeometry(QtCore.QRect(630, 240, 81, 31))
        self.StopBut.setObjectName("StopBut")
        self.BlurSlide = QtWidgets.QSlider(self.centralwidget)
        self.BlurSlide.setGeometry(QtCore.QRect(520, 160, 160, 22))
        self.BlurSlide.setOrientation(QtCore.Qt.Horizontal)
        self.BlurSlide.setObjectName("BlurSlide")
        self.ContrastSlide = QtWidgets.QSlider(self.centralwidget)
        self.ContrastSlide.setGeometry(QtCore.QRect(520, 90, 160, 22))
        self.ContrastSlide.setOrientation(QtCore.Qt.Horizontal)
        self.ContrastSlide.setObjectName("ContrastSlide")
        self.BrightnessSlide = QtWidgets.QSlider(self.centralwidget)
        self.BrightnessSlide.setGeometry(QtCore.QRect(520, 30, 160, 22))
        self.BrightnessSlide.setOrientation(QtCore.Qt.Horizontal)
        self.BrightnessSlide.setObjectName("BrightnessSlide")
        self.ManualMode = QtWidgets.QRadioButton(self.centralwidget)
        self.ManualMode.setGeometry(QtCore.QRect(30, 290, 77, 23))
        self.ManualMode.setStyleSheet("font: 12pt \"Consolas\";")
        self.ManualMode.setObjectName("ManualMode")
        self.AutoMode = QtWidgets.QRadioButton(self.centralwidget)
        self.AutoMode.setGeometry(QtCore.QRect(110, 290, 149, 23))
        self.AutoMode.setStyleSheet("font: 12pt \"Consolas\";")
        self.AutoMode.setObjectName("AutoMode")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 381, 221))
        self.label.setObjectName("label")
        self.Brightness = QtWidgets.QTextEdit(self.centralwidget)
        self.Brightness.setGeometry(QtCore.QRect(570, 0, 71, 31))
        self.Brightness.setObjectName("Brightness")
        self.Contrast = QtWidgets.QTextEdit(self.centralwidget)
        self.Contrast.setGeometry(QtCore.QRect(560, 60, 121, 31))
        self.Contrast.setObjectName("Contrast")
        self.Blur = QtWidgets.QTextEdit(self.centralwidget)
        self.Blur.setGeometry(QtCore.QRect(560, 130, 91, 31))
        self.Blur.setObjectName("Blur")
        self.Settings = QtWidgets.QTextEdit(self.centralwidget)
        self.Settings.setGeometry(QtCore.QRect(70, 250, 121, 31))
        self.Settings.setMinimumSize(QtCore.QSize(81, 21))
        self.Settings.setObjectName("Settings")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartBut.setText(_translate("MainWindow", "Start"))
        self.StopBut.setText(_translate("MainWindow", "Stop"))
        self.ManualMode.setText(_translate("MainWindow", "Ручная"))
        self.AutoMode.setText(_translate("MainWindow", "Автоматическая"))
        self.label.setText(_translate("MainWindow", "CameraView"))
        self.Brightness.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; resize:none; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Яркость</span></p></body></html>"))
        self.Contrast.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Контрастность</span></p></body></html>"))
        self.Blur.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Размытие</span></p></body></html>"))
        self.Settings.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:12pt;\">Настройка</span></p></body></html>"))
